version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=file:./dev.db
      - LMSTUDIO_API_URL=http://host.docker.internal:1234/v1/chat/completions
      - PORT=3001
      - CORS_ORIGIN=https://bookmarks.twoja-domena.pl
    volumes:
      - ./backend/prisma/dev.db:/app/prisma/dev.db
    networks:
      - taskflow-network

  frontend:
    build: ./taskflow
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=https://bookmarks-api.twoja-domena.pl/api
    depends_on:
      - backend
    networks:
      - taskflow-network

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_NAME=taskflow-bookmarks
    volumes:
      - ~/.cloudflared:/etc/cloudflared
    depends_on:
      - backend
      - frontend
    networks:
      - taskflow-network

networks:
  taskflow-network:
    driver: bridge 